create extension if not exists pgcrypto;
create table if not exists website_settings(id boolean primary key default true,store_name text not null default 'FlowGet',tagline text,logo_url text,mobile_logo_url text,favicon_url text,browser_title text,meta_description text,search_placeholder text default 'Search products...',footer_about text,phone text,email text,primary text default '#f97316',primary_hover text default '#ea580c',secondary text default '#111827',delivery_dhaka numeric default 80,delivery_outside numeric default 140,currency text default '৳',updated_at timestamptz default now());
insert into website_settings(id) values(true) on conflict(id) do nothing;
create table if not exists categories(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,icon text,image_url text,description text,seo_title text,seo_description text,sort_order int default 0,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists products(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,specifications jsonb default '{}'::jsonb,category_id uuid references categories(id) on delete set null,brand text,sku text unique,price numeric not null check(price>=0),discount_price numeric check(discount_price is null or discount_price>=0),stock int not null default 0 check(stock>=0),main_image text,rating numeric default 0,review_count int default 0,featured boolean default false,new_arrival boolean default false,flash_deal boolean default false,is_best_selling boolean default false,active boolean default true,seo_title text,meta_description text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references products(id) on delete cascade,url text not null,sort_order int default 0,created_at timestamptz default now());
create table if not exists customers(id uuid primary key default gen_random_uuid(),name text,phone text unique,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists coupons(id uuid primary key default gen_random_uuid(),code text unique not null,coupon_type text not null check(coupon_type in('percentage','fixed')),discount_value numeric not null,min_order numeric default 0,max_discount numeric,usage_limit int,per_customer_limit int default 1,start_at timestamptz,expires_at timestamptz,active boolean default true,created_at timestamptz default now());
create table if not exists orders(id uuid primary key default gen_random_uuid(),order_id text unique not null,customer_id uuid references customers(id),customer_name text not null,phone text not null,division text,district text,area text,address text not null,note text,subtotal numeric not null,discount numeric default 0,coupon_code text,delivery_charge numeric not null,payment_method text not null,total numeric not null,status text not null default 'Pending' check(status in('Pending','Confirmed','Processing','Shipped','Delivered','Cancelled')),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,product_id uuid not null references products(id),product_name text not null,sku text,quantity int not null check(quantity>0),unit_price numeric not null,line_total numeric not null);
create table if not exists coupon_usage(id uuid primary key default gen_random_uuid(),coupon_id uuid not null references coupons(id) on delete cascade,order_id uuid not null references orders(id) on delete cascade,phone text not null,discount numeric not null,created_at timestamptz default now());
create table if not exists banners(id uuid primary key default gen_random_uuid(),title text,subtitle text,button_text text,button_url text,image_url text,mobile_image_url text,start_at timestamptz,end_at timestamptz,sort_order int default 0,active boolean default true,created_at timestamptz default now());
create table if not exists advertisements(id uuid primary key default gen_random_uuid(),title text,text_content text,image_url text,cta_text text,destination_url text,placement text,start_at timestamptz,end_at timestamptz,active boolean default true,created_at timestamptz default now());
create table if not exists homepage_sections(id uuid primary key default gen_random_uuid(),section_type text not null,title text,subtitle text,config jsonb default '{}'::jsonb,sort_order int default 0,active boolean default true,created_at timestamptz default now());
create table if not exists payment_methods(id uuid primary key default gen_random_uuid(),name text not null,account_number text,merchant_number text,instructions text,transaction_instructions text,active boolean default false,sort_order int default 0);
create table if not exists navigation_items(id uuid primary key default gen_random_uuid(),label text not null,url text not null,sort_order int default 0,active boolean default true);
create table if not exists pages(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,content text,seo_title text,meta_description text,active boolean default true,updated_at timestamptz default now());
create table if not exists analytics_events(id bigint generated always as identity primary key,event_name text not null,path text,product_id uuid references products(id) on delete set null,metadata jsonb default '{}'::jsonb,session_id text,created_at timestamptz default now());
create table if not exists visitor_sessions(id text primary key,started_at timestamptz default now(),ended_at timestamptz,device_type text,referrer text,last_path text);
create table if not exists reviews(id uuid primary key default gen_random_uuid(),product_id uuid references products(id) on delete cascade,customer_name text,rating int check(rating between 1 and 5),review_text text,approved boolean default false,created_at timestamptz default now());
create index if not exists products_category_idx on products(category_id);create index if not exists products_active_idx on products(active);create index if not exists orders_phone_idx on orders(phone);create index if not exists orders_status_idx on orders(status);create index if not exists analytics_events_created_idx on analytics_events(created_at);
create table if not exists admin_users(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz default now());create table if not exists order_counters(order_date date primary key,last_number int not null default 0);
create or replace function is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from admin_users where user_id=auth.uid())$$;
create or replace function next_order_id() returns text language plpgsql security definer set search_path=public as $$declare d date:=current_date;n int;begin insert into order_counters(order_date,last_number) values(d,1) on conflict(order_date) do update set last_number=order_counters.last_number+1 returning last_number into n; return 'FG-'||to_char(d,'YYYYMMDD')||'-'||lpad(n::text,6,'0');end$$;
create or replace function track_order(p_order_id text,p_phone text) returns table(order_id text,status text,created_at timestamptz) language sql security definer set search_path=public as $$select o.order_id,o.status,o.created_at from orders o where upper(o.order_id)=upper(trim(p_order_id)) and regexp_replace(o.phone,'[^0-9]','','g')=regexp_replace(trim(p_phone),'[^0-9]','','g') limit 1$$;
create or replace function create_order_secure(p_customer_name text,p_phone text,p_division text,p_district text,p_area text,p_address text,p_note text,p_items jsonb,p_coupon text,p_delivery_area text,p_payment_method text) returns jsonb language plpgsql security definer set search_path=public as $$declare item jsonb;p products%rowtype;o orders%rowtype;sub numeric:=0;disc numeric:=0;del numeric;cid uuid;cp coupons%rowtype;qty int;oid text;cust uuid;clean_phone text:=regexp_replace(trim(p_phone),'[^0-9]','','g');begin
 if length(trim(coalesce(p_customer_name,'')))<2 then raise exception 'Please enter your name';end if;
 if clean_phone !~ '^01[0-9]{9}$' then raise exception 'Invalid Bangladesh phone number';end if;
 if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty';end if;
 if lower(trim(coalesce(p_payment_method,'')))<>'cash on delivery' then raise exception 'Invalid payment method';end if;
 for item in select * from jsonb_array_elements(p_items) loop
   begin qty:=(item->>'quantity')::int; exception when others then raise exception 'Invalid quantity'; end;
   select * into p from products where id=(item->>'product_id')::uuid and active=true for update;
   if not found then raise exception 'Product unavailable';end if;
   if qty<1 or qty>p.stock then raise exception 'Insufficient stock for %',p.name;end if;
   sub:=sub+coalesce(p.discount_price,p.price)*qty;
 end loop;
 if p_coupon is not null and trim(p_coupon)<>'' then
   select * into cp from coupons where upper(code)=upper(trim(p_coupon)) and active=true and (start_at is null or now()>=start_at) and (expires_at is null or now()<=expires_at) for update;
   if not found then raise exception 'Invalid coupon';end if;
   if sub<coalesce(cp.min_order,0) then raise exception 'Minimum order amount not reached';end if;
   if cp.usage_limit is not null and (select count(*) from coupon_usage where coupon_id=cp.id)>=cp.usage_limit then raise exception 'Coupon usage limit exceeded';end if;
   if cp.per_customer_limit is not null and (select count(*) from coupon_usage where coupon_id=cp.id and phone=clean_phone)>=cp.per_customer_limit then raise exception 'This coupon has reached its limit for this customer';end if;
   if cp.coupon_type='percentage' then disc:=least(sub*cp.discount_value/100,coalesce(cp.max_discount,sub));else disc:=least(cp.discount_value,sub);end if;
 end if;
 select case when lower(trim(coalesce(p_delivery_area,'')))='dhaka' then delivery_dhaka else delivery_outside end into del from website_settings where id=true;
 del:=coalesce(del,0); oid:=next_order_id();
 insert into customers(name,phone) values(p_customer_name,clean_phone) on conflict(phone) do update set name=excluded.name,updated_at=now() returning id into cust;
 insert into orders(order_id,customer_id,customer_name,phone,division,district,area,address,note,subtotal,discount,coupon_code,delivery_charge,payment_method,total) values(oid,cust,p_customer_name,clean_phone,p_division,p_district,p_area,p_address,p_note,sub,disc,nullif(trim(p_coupon),''),del,'Cash on Delivery',sub-disc+del) returning * into o;
 for item in select * from jsonb_array_elements(p_items) loop
   select * into p from products where id=(item->>'product_id')::uuid for update;qty:=(item->>'quantity')::int;
   insert into order_items(order_id,product_id,product_name,sku,quantity,unit_price,line_total) values(o.id,p.id,p.name,p.sku,qty,coalesce(p.discount_price,p.price),coalesce(p.discount_price,p.price)*qty);
   update products set stock=stock-qty,updated_at=now() where id=p.id;
 end loop;
 if cp.id is not null then insert into coupon_usage(coupon_id,order_id,phone,discount) values(cp.id,o.id,clean_phone,disc);end if;
 return jsonb_build_object('id',o.id,'order_id',o.order_id,'total',o.total,'status',o.status);
end$$;
create or replace function cancel_order_secure(p_order_uuid uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare o orders%rowtype;i record;p products%rowtype;begin if not is_admin() then raise exception 'Not authorized';end if;select * into o from orders where id=p_order_uuid for update;if not found then raise exception 'Order not found';end if;if o.status='Cancelled' then return jsonb_build_object('id',o.id,'status',o.status);end if;if o.status='Delivered' then raise exception 'Delivered orders cannot be cancelled';end if;for i in select product_id,quantity from order_items where order_id=o.id loop select * into p from products where id=i.product_id for update;if found then update products set stock=stock+i.quantity,updated_at=now() where id=p.id;end if;end loop;update orders set status='Cancelled',updated_at=now() where id=o.id;return jsonb_build_object('id',o.id,'status','Cancelled');end$$;
create or replace function touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
alter table website_settings enable row level security;alter table categories enable row level security;alter table products enable row level security;alter table product_images enable row level security;alter table banners enable row level security;alter table advertisements enable row level security;alter table homepage_sections enable row level security;alter table payment_methods enable row level security;alter table pages enable row level security;alter table reviews enable row level security;alter table orders enable row level security;alter table order_items enable row level security;alter table coupons enable row level security;alter table coupon_usage enable row level security;alter table analytics_events enable row level security;alter table visitor_sessions enable row level security;alter table admin_users enable row level security;
create policy "public settings read" on website_settings for select using(true);create policy "public categories read" on categories for select using(active=true);create policy "public products read" on products for select using(active=true);create policy "public images read" on product_images for select using(true);create policy "public banners read" on banners for select using(active=true);create policy "public ads read" on advertisements for select using(active=true);create policy "public homepage read" on homepage_sections for select using(active=true);create policy "public pages read" on pages for select using(active=true);create policy "public reviews read" on reviews for select using(approved=true);create policy "admin all settings" on website_settings for all using(is_admin()) with check(is_admin());create policy "admin all categories" on categories for all using(is_admin()) with check(is_admin());create policy "admin all products" on products for all using(is_admin()) with check(is_admin());create policy "admin all images" on product_images for all using(is_admin()) with check(is_admin());create policy "admin all banners" on banners for all using(is_admin()) with check(is_admin());create policy "admin all ads" on advertisements for all using(is_admin()) with check(is_admin());create policy "admin all homepage" on homepage_sections for all using(is_admin()) with check(is_admin());create policy "admin all payments" on payment_methods for all using(is_admin()) with check(is_admin());create policy "admin all pages" on pages for all using(is_admin()) with check(is_admin());create policy "admin all reviews" on reviews for all using(is_admin()) with check(is_admin());create policy "admin all orders" on orders for select,update using(is_admin()) with check(is_admin());create policy "admin all items" on order_items for select using(is_admin());create policy "admin all coupons" on coupons for all using(is_admin()) with check(is_admin());create policy "admin all coupon usage" on coupon_usage for select using(is_admin());create policy "admin analytics" on analytics_events for select using(is_admin());create policy "public analytics insert" on analytics_events for insert with check(true);create policy "admin sessions" on visitor_sessions for all using(is_admin()) with check(is_admin());create policy "public session insert" on visitor_sessions for insert with check(true);


do $$begin
 if not exists (select 1 from pg_constraint where conname='products_discount_not_above_price') then alter table products add constraint products_discount_not_above_price check(discount_price is null or discount_price<=price);end if;
 if not exists (select 1 from pg_constraint where conname='coupons_positive_discount') then alter table coupons add constraint coupons_positive_discount check(discount_value>0);end if;
 if not exists (select 1 from pg_constraint where conname='website_delivery_dhaka_nonnegative') then alter table website_settings add constraint website_delivery_dhaka_nonnegative check(delivery_dhaka>=0);end if;
 if not exists (select 1 from pg_constraint where conname='website_delivery_outside_nonnegative') then alter table website_settings add constraint website_delivery_outside_nonnegative check(delivery_outside>=0);end if;
end$$;

drop trigger if exists categories_touch_updated_at on categories;create trigger categories_touch_updated_at before update on categories for each row execute function touch_updated_at();
drop trigger if exists products_touch_updated_at on products;create trigger products_touch_updated_at before update on products for each row execute function touch_updated_at();
drop trigger if exists customers_touch_updated_at on customers;create trigger customers_touch_updated_at before update on customers for each row execute function touch_updated_at();
drop trigger if exists orders_touch_updated_at on orders;create trigger orders_touch_updated_at before update on orders for each row execute function touch_updated_at();
drop trigger if exists pages_touch_updated_at on pages;create trigger pages_touch_updated_at before update on pages for each row execute function touch_updated_at();
