-- SparkCart Mall: Visitor Activity + Telegram notification support
-- SAFE / ADDITIVE ONLY: no existing product/order/customer rows are deleted.
-- Run AFTER your existing migrations.

alter table public.orders add column if not exists visitor_id text;
create index if not exists orders_visitor_id_idx on public.orders(visitor_id);

create table if not exists public.anonymous_visitors (
  visitor_id text primary key,
  first_visit timestamptz not null default now(),
  last_active timestamptz not null default now(),
  page_views integer not null default 0 check (page_views >= 0)
);
alter table public.anonymous_visitors enable row level security;

drop policy if exists "Admin can read anonymous visitors" on public.anonymous_visitors;
create policy "Admin can read anonymous visitors" on public.anonymous_visitors
for select to authenticated using (public.is_sparkcart_admin());

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null references public.anonymous_visitors(visitor_id) on delete cascade,
  event_type text not null check (event_type in ('visit','page_view','product_view','add_to_cart','remove_from_cart','checkout_visit','checkout_started','order_completed')),
  product_id uuid references public.products(id) on delete set null,
  order_id text,
  created_at timestamptz not null default now()
);
create index if not exists visitor_events_visitor_created_idx on public.visitor_events(visitor_id, created_at desc);
create index if not exists visitor_events_type_created_idx on public.visitor_events(event_type, created_at desc);
create index if not exists visitor_events_product_created_idx on public.visitor_events(product_id, created_at desc);
create index if not exists visitor_events_order_idx on public.visitor_events(order_id);
alter table public.visitor_events enable row level security;

drop policy if exists "Admin can read visitor events" on public.visitor_events;
create policy "Admin can read visitor events" on public.visitor_events
for select to authenticated using (public.is_sparkcart_admin());

create or replace function public.record_visitor_event(p_visitor_id text, p_event_type text, p_product_id uuid default null, p_order_id text default null)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if p_visitor_id is null or length(trim(p_visitor_id)) < 3 or length(trim(p_visitor_id)) > 64 then
    raise exception 'Invalid visitor id';
  end if;
  if p_event_type not in ('visit','page_view','product_view','add_to_cart','remove_from_cart','checkout_visit','checkout_started','order_completed') then
    raise exception 'Invalid visitor event';
  end if;
  insert into public.anonymous_visitors(visitor_id) values (trim(p_visitor_id))
  on conflict(visitor_id) do update set last_active=now();
  update public.anonymous_visitors
    set last_active=now(),
        page_views=page_views + case when p_event_type='page_view' then 1 else 0 end
    where visitor_id=trim(p_visitor_id);
  insert into public.visitor_events(visitor_id,event_type,product_id,order_id)
  values(trim(p_visitor_id),p_event_type,p_product_id,p_order_id);
end;
$$;
revoke all on function public.record_visitor_event(text,text,uuid,text) from public;
grant execute on function public.record_visitor_event(text,text,uuid,text) to anon, authenticated;

-- Fix the public order insert policy from the previous feature migration so COD remains valid
-- while preserving the same pending-order/phone validation.
drop policy if exists "Public can insert orders" on public.orders;
drop policy if exists "Public can submit online orders" on public.orders;
create policy "Public can insert orders"
on public.orders for insert to anon
with check (
  status='pending'
  and payment_method in ('Cash on Delivery','bKash','Nagad','Rocket')
  and customer_phone ~ '^01[0-9]{9}$'
);

-- Prevent a visitor link from being used as a substitute for order tracking security.
-- The existing track_order(order_id, phone) RPC remains unchanged.

create table if not exists public.order_notification_log (
  order_id text primary key,
  notified_at timestamptz not null default now()
);
alter table public.order_notification_log enable row level security;
drop policy if exists "Admin can read notification log" on public.order_notification_log;
create policy "Admin can read notification log" on public.order_notification_log
for select to authenticated using (public.is_sparkcart_admin());
