import React,{useEffect,useState}from'react';
import{supabase}from'../lib/supabase';
import{getProducts,getCategories,getSettings}from'../lib/store';
import{Upload,Image as ImageIcon,Video,Menu,X}from'lucide-react';
const TABS=['dashboard','products','categories','orders','coupons','banners','settings'];
const emptyProduct={name:'',slug:'',description:'',category_id:'',brand:'',sku:'',price:'',discount_price:'',stock:'0',main_image:'',video_url:'',active:true};
const emptyCategory={name:'',slug:'',description:'',icon:'✦',sort_order:0,active:true};
const emptyCoupon={code:'',coupon_type:'percentage',discount_value:'',min_order:0,max_discount:'',usage_limit:'',per_customer_limit:1,start_at:'',expires_at:'',active:true};
const emptyBanner={title:'',subtitle:'',button_text:'Shop Now',button_url:'/shop',image_url:'',mobile_image_url:'',start_at:'',end_at:'',sort_order:0,active:true};

async function uploadMedia(file,folder){
  if(!supabase)throw new Error('Supabase is not configured.');
  if(!file)throw new Error('Please choose a file.');
  const ext=(file.name.split('.').pop()||'bin').toLowerCase();
  const safe=file.name.replace(/[^a-z0-9._-]/gi,'-').toLowerCase();
  const path=`${folder}/${Date.now()}-${Math.random().toString(36).slice(2,9)}-${safe||`file.${ext}`}`;
  const{error}=await supabase.storage.from('product-media').upload(path,file,{upsert:false,cacheControl:'3600'});
  if(error)throw error;
  return supabase.storage.from('product-media').getPublicUrl(path).data.publicUrl;
}

export default function Admin(){
  const[user,setUser]=useState(null),[admin,setAdmin]=useState(false),[tab,setTab]=useState('dashboard'),[err,setErr]=useState(''),[menu,setMenu]=useState(false);
  useEffect(()=>{if(!supabase)return;let alive=true;supabase.auth.getSession().then(async({data})=>{const u=data.session?.user||null;if(!alive)return;setUser(u);if(u){const{data:a}=await supabase.rpc('is_admin');setAdmin(Boolean(a))}});const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{const u=s?.user||null;setUser(u);setAdmin(false);if(u)setTimeout(async()=>{const{data:a}=await supabase.rpc('is_admin');setAdmin(Boolean(a))},0)});return()=>{alive=false;sub.subscription.unsubscribe()};},[]);
  if(!supabase)return <div className="container"><div className="card"><h1>Admin Setup</h1><p>Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your environment.</p></div></div>;
  if(!user)return <AdminLogin/>;
  if(!admin)return <div className="container"><div className="card admin-denied"><h1>Access denied</h1><p>Your account is signed in, but it is not an approved FlowGet administrator.</p><button className="btn" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></div>;
  return <div className="adminwrap">
    <aside className={`adminnav ${menu?'open':''}`}>
      <div className="adminnavtop"><h2>FlowGet Admin</h2><button className="adminmenubtn" onClick={()=>setMenu(!menu)} aria-label="Toggle admin menu">{menu?<X/>:<Menu/>}</button></div>
      <div className="adminnavlinks">{TABS.map(x=><button className={tab===x?'active':''} onClick={()=>{setErr('');setTab(x);setMenu(false)}} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}<button onClick={()=>supabase.auth.signOut()}>Logout</button></div>
    </aside>
    <section className="adminmain"><div className="adminhead"><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1>{err&&<div className="notice" role="alert">{err}</div>}</div>{tab==='dashboard'?<Dashboard/>:tab==='settings'?<Settings/>:tab==='products'?<Products setErr={setErr}/>:tab==='categories'?<Categories setErr={setErr}/>:tab==='orders'?<Orders setErr={setErr}/>:tab==='coupons'?<Coupons setErr={setErr}/>:<Banners setErr={setErr}/>}</section>
  </div>
}
function AdminLogin(){const[e,setE]=useState({email:'',password:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);return <div className="container"><div className="card adminlogin"><h1>🔐 FlowGet Admin</h1><p className="muted">Phone থেকে product ও order manage করুন।</p><form onSubmit={async x=>{x.preventDefault();setErr('');setBusy(true);const{error}=await supabase.auth.signInWithPassword(e);setBusy(false);if(error)setErr(error.message.includes('Invalid login')?'Invalid email or password.':error.message)}}><Text f="email" type="email" v={e.email} set={v=>setE({...e,email:v})}/><Text f="password" type="password" v={e.password} set={v=>setE({...e,password:v})}/><button className="btn" disabled={busy}>{busy?'Logging in…':'Login'}</button>{err&&<div className="notice" role="alert">{err}</div>}</form></div></div>}
function Dashboard(){const[s,setS]=useState({orders:0,products:0,pending:0,sales:0});useEffect(()=>{Promise.all([supabase.from('orders').select('id,total,status'),supabase.from('products').select('id')]).then(([o,p])=>{const rows=o.data||[];setS({orders:rows.length,products:(p.data||[]).length,pending:rows.filter(x=>x.status==='Pending').length,sales:rows.filter(x=>x.status!=='Cancelled').reduce((a,x)=>a+Number(x.total||0),0)})})},[]);return <div className="admincards"><div className="stat">Orders<strong>{s.orders}</strong></div><div className="stat">Pending<strong>{s.pending}</strong></div><div className="stat">Products<strong>{s.products}</strong></div><div className="stat">Sales<strong>৳{s.sales}</strong></div></div>}
function Products({setErr}){const[data,setData]=useState([]),[cats,setCats]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState(emptyProduct),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[galleryUrls,setGalleryUrls]=useState([]);const load=()=>Promise.all([getProducts({}),getCategories()]).then(([p,c])=>{setData(p);setCats(c)}).catch(e=>setErr(e.message));useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();setErr('');setSaving(true);try{const payload={...form,price:Number(form.price),discount_price:form.discount_price===''?null:Number(form.discount_price),stock:Number(form.stock),category_id:form.category_id||null,sku:form.sku||null,video_url:form.video_url||null};const r=editing?await supabase.from('products').update(payload).eq('id',editing):await supabase.from('products').insert(payload).select('id').single();if(r.error)throw r.error;const productId=editing||r.data?.id;if(galleryUrls.length&&productId){const{error}=await supabase.from('product_images').insert(galleryUrls.map((url,i)=>({product_id:productId,url,sort_order:i})));if(error)throw error}setEditing(null);setForm(emptyProduct);setGalleryUrls([]);load()}catch(e){setErr(e.message)}finally{setSaving(false)}};
 const edit=p=>setForm({...emptyProduct,...p,category_id:p.category_id||'',price:p.price??'',discount_price:p.discount_price??'',stock:p.stock??0,video_url:p.video_url||''});
 const handleImage=async(e,multiple=false)=>{const files=[...e.target.files];if(!files.length)return;setUploading(true);try{const urls=[];for(const file of files){if(!file.type.startsWith('image/'))throw new Error('Only image files are allowed.');urls.push(await uploadMedia(file,'products'))}setForm(f=>({...f,main_image:multiple?(f.main_image||urls[0]):urls[0]}));if(multiple)setGalleryUrls(g=>[...g,...urls]);if(editing&&multiple){const rows=urls.map((url,i)=>({product_id:editing,url,sort_order:i+1}));const{error}=await supabase.from('product_images').insert(rows);if(error)throw error}if(editing)load()}catch(e){setErr(e.message)}finally{setUploading(false);e.target.value=''}};
 const handleVideo=async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{if(!file.type.startsWith('video/'))throw new Error('Please choose a video file.');const url=await uploadMedia(file,'videos');setForm(f=>({...f,video_url:url}))}catch(e){setErr(e.message)}finally{setUploading(false);e.target.value=''}};
 return <><Editor title={editing?'Edit Product':'Add Product'} onSubmit={save} onCancel={()=>{setEditing(null);setForm(emptyProduct);setGalleryUrls([])}} saving={saving} fields={<><Text f="name" v={form.name} set={v=>setForm({...form,name:v})}/><Text f="slug" v={form.slug} set={v=>setForm({...form,slug:v})}/><Text f="sku" v={form.sku||''} set={v=>setForm({...form,sku:v})}/><Text f="brand" v={form.brand||''} set={v=>setForm({...form,brand:v})}/><div className="field"><label>Category</label><select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">No category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="two"><Text f="price" type="number" v={form.price} set={v=>setForm({...form,price:v})}/><Text f="discount_price" type="number" v={form.discount_price} set={v=>setForm({...form,discount_price:v})}/></div><Text f="stock" type="number" v={form.stock} set={v=>setForm({...form,stock:v})}/><div className="uploadgrid"><div className="uploadbox"><label><ImageIcon size={18}/> Main product image<input type="file" accept="image/*" onChange={handleImage}/></label><small>JPG, PNG, WebP etc.</small>{form.main_image&&<img className="uploadpreview" src={form.main_image} alt="Product preview"/>}</div><div className="uploadbox"><label><ImageIcon size={18}/> Gallery images<input type="file" accept="image/*" multiple onChange={e=>handleImage(e,true)}/></label><small>For existing products, images are saved to the gallery.</small></div><div className="uploadbox"><label><Video size={18}/> Product video<input type="file" accept="video/*" onChange={handleVideo}/></label><small>Upload MP4/WebM or paste a video URL.</small></div></div><Text f="main_image_url" v={form.main_image||''} set={v=>setForm({...form,main_image:v})}/><Text f="video_url" v={form.video_url||''} set={v=>setForm({...form,video_url:v})}/><div className="field"><label>Description</label><textarea rows="4" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label>{uploading&&<div className="notice">Uploading media…</div>}</>}/><Table columns={['name','sku','price','stock','active']} data={data} onEdit={p=>{setEditing(p.id);setGalleryUrls([]);edit(p)}} onDelete={async p=>{if(confirm(`Delete ${p.name}?`)){const{error}=await supabase.from('products').delete().eq('id',p.id);if(error)setErr(error.message);else load()}}}/></>}
function Categories({setErr}){const[data,setData]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState(emptyCategory);const load=()=>getCategories().then(setData).catch(e=>setErr(e.message));useEffect(load,[]);const save=async e=>{e.preventDefault();const payload={...form,sort_order:Number(form.sort_order||0)};const{error}=editing?await supabase.from('categories').update(payload).eq('id',editing):await supabase.from('categories').insert(payload);if(error)setErr(error.message);else{setEditing(null);setForm(emptyCategory);load()}};return <><Editor title={editing?'Edit Category':'Add Category'} onSubmit={save} onCancel={()=>{setEditing(null);setForm(emptyCategory)}} fields={<><Text f="name" v={form.name} set={v=>setForm({...form,name:v})}/><Text f="slug" v={form.slug} set={v=>setForm({...form,slug:v})}/><Text f="icon" v={form.icon} set={v=>setForm({...form,icon:v})}/><Text f="sort_order" type="number" v={form.sort_order} set={v=>setForm({...form,sort_order:v})}/><div className="field"><label>Description</label><textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label></>}/><Table columns={['name','slug','sort_order','active']} data={data} onEdit={p=>{setEditing(p.id);setForm({...emptyCategory,...p})}} onDelete={async p=>{if(confirm(`Delete ${p.name}?`)){const{error}=await supabase.from('categories').delete().eq('id',p.id);if(error)setErr(error.message);else load()}}}/></>}
function Orders({setErr}){const[data,setData]=useState([]);const load=()=>supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(200).then(({data,error})=>{if(error)setErr(error.message);else setData(data||[])});useEffect(load,[]);const update=async(id,status)=>{if(status==='Cancelled'){const{error}=await supabase.rpc('cancel_order_secure',{p_order_uuid:id});if(error)setErr(error.message);else load();return}const{error}=await supabase.rpc('update_order_status_secure',{p_order_uuid:id,p_status:status});if(error)setErr(error.message);else load()};return <div className="tablewrap"><table><thead><tr>{['order_id','customer_name','phone','total','status','created_at'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.map(o=><tr key={o.id}><td>{o.order_id}</td><td>{o.customer_name}</td><td>{o.phone}</td><td>৳{o.total}</td><td><select value={o.status} onChange={e=>update(o.id,e.target.value)}>{['Pending','Confirmed','Processing','Shipped','Delivered','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></td><td>{new Date(o.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}
function Coupons({setErr}){const[data,setData]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState(emptyCoupon);const load=()=>supabase.from('coupons').select('*').order('created_at',{ascending:false}).then(({data,error})=>{if(error)setErr(error.message);else setData(data||[])});useEffect(load,[]);const save=async e=>{e.preventDefault();const payload={...form,code:form.code.trim().toUpperCase(),discount_value:Number(form.discount_value),min_order:Number(form.min_order||0),max_discount:form.max_discount===''?null:Number(form.max_discount),usage_limit:form.usage_limit===''?null:Number(form.usage_limit),per_customer_limit:form.per_customer_limit===''?null:Number(form.per_customer_limit),start_at:form.start_at||null,expires_at:form.expires_at||null};const{error}=editing?await supabase.from('coupons').update(payload).eq('id',editing):await supabase.from('coupons').insert(payload);if(error)setErr(error.message);else{setEditing(null);setForm(emptyCoupon);load()}};return <><Editor title={editing?'Edit Coupon':'Add Coupon'} onSubmit={save} onCancel={()=>{setEditing(null);setForm(emptyCoupon)}} fields={<><Text f="code" v={form.code} set={v=>setForm({...form,code:v})}/><div className="two"><div className="field"><label>Type</label><select value={form.coupon_type} onChange={e=>setForm({...form,coupon_type:e.target.value})}><option>percentage</option><option>fixed</option></select></div><Text f="discount_value" type="number" v={form.discount_value} set={v=>setForm({...form,discount_value:v})}/></div><div className="two"><Text f="min_order" type="number" v={form.min_order} set={v=>setForm({...form,min_order:v})}/><Text f="max_discount" type="number" v={form.max_discount} set={v=>setForm({...form,max_discount:v})}/></div><div className="two"><Text f="usage_limit" type="number" v={form.usage_limit} set={v=>setForm({...form,usage_limit:v})}/><Text f="per_customer_limit" type="number" v={form.per_customer_limit} set={v=>setForm({...form,per_customer_limit:v})}/></div><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label></>}/><Table columns={['code','coupon_type','discount_value','usage_limit','per_customer_limit','active']} data={data} onEdit={p=>{setEditing(p.id);setForm({...emptyCoupon,...p})}} onDelete={async p=>{if(confirm(`Delete ${p.code}?`)){const{error}=await supabase.from('coupons').delete().eq('id',p.id);if(error)setErr(error.message);else load()}}}/></>}
function Banners({setErr}){const[data,setData]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState(emptyBanner);const load=()=>supabase.from('banners').select('*').order('sort_order').then(({data,error})=>{if(error)setErr(error.message);else setData(data||[])});useEffect(load,[]);const save=async e=>{e.preventDefault();const payload={...form,sort_order:Number(form.sort_order||0),start_at:form.start_at||null,end_at:form.end_at||null};const{error}=editing?await supabase.from('banners').update(payload).eq('id',editing):await supabase.from('banners').insert(payload);if(error)setErr(error.message);else{setEditing(null);setForm(emptyBanner);load()}};return <><Editor title={editing?'Edit Banner':'Add Banner'} onSubmit={save} onCancel={()=>{setEditing(null);setForm(emptyBanner)}} fields={<><Text f="title" v={form.title} set={v=>setForm({...form,title:v})}/><Text f="subtitle" v={form.subtitle} set={v=>setForm({...form,subtitle:v})}/><Text f="button_text" v={form.button_text} set={v=>setForm({...form,button_text:v})}/><Text f="button_url" v={form.button_url} set={v=>setForm({...form,button_url:v})}/><Text f="image_url" v={form.image_url} set={v=>setForm({...form,image_url:v})}/><Text f="mobile_image_url" v={form.mobile_image_url} set={v=>setForm({...form,mobile_image_url:v})}/><Text f="sort_order" type="number" v={form.sort_order} set={v=>setForm({...form,sort_order:v})}/><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label></>}/><Table columns={['title','button_url','sort_order','active']} data={data} onEdit={p=>{setEditing(p.id);setForm({...emptyBanner,...p})}} onDelete={async p=>{if(confirm(`Delete banner?`)){const{error}=await supabase.from('banners').delete().eq('id',p.id);if(error)setErr(error.message);else load()}}}/></>}
function Settings(){const[s,setS]=useState({});useEffect(()=>{getSettings().then(setS)},[]);const save=async()=>{const payload={...s,delivery_dhaka:Number(s.delivery_dhaka),delivery_outside:Number(s.delivery_outside),updated_at:new Date().toISOString()};const{error}=await supabase.from('website_settings').upsert(payload);if(error)alert(error.message);else setS(payload)};return <div className="card" style={{maxWidth:760}}><h2>Website Settings</h2>{['store_name','tagline','phone','email','browser_title','meta_description','search_placeholder','footer_about','primary','primary_hover','delivery_dhaka','delivery_outside'].map(k=><Text key={k} f={k} v={s[k]??''} set={v=>setS({...s,[k]:v})}/>)}<button className="btn" onClick={save}>Save Settings</button></div>}
function Text({f,v,set,type='text'}){return <div className="field"><label>{f.replaceAll('_',' ')}</label><input type={type} value={v??''} onChange={e=>set(e.target.value)}/></div>}
function Editor({title,onSubmit,onCancel,fields,saving=false}){return <form className="card admineditor" onSubmit={onSubmit}><div className="admineditorhead"><h2>{title}</h2><button type="button" onClick={onCancel}>Reset</button></div>{fields}<button className="btn" disabled={saving}>{saving?'Saving…':'Save'}</button></form>}
function Table({columns,data,onEdit,onDelete}){return <div className="tablewrap"><table><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}<th>actions</th></tr></thead><tbody>{data.map(r=><tr key={r.id}>{columns.map(k=><td key={k}>{String(r[k]??'').slice(0,80)}</td>)}<td><div className="tableactions"><button onClick={()=>onEdit(r)}>Edit</button><button onClick={()=>onDelete(r)}>Delete</button></div></td></tr>)}{!data.length&&<tr><td colSpan={columns.length+1}>No records.</td></tr>}</tbody></table></div>}
